### ISSUE TITLE
Does not work with Nifi 1.9.2

### ISSUE THREAD

**Issue by dp1140a** [influxdata/nifi-influxdb-bundle#18]
When I try to use the processor in the latest version of Nifi (1.9.2) it states that it is not compatible.  This does work with 1.9.0

**Comment by bednar** [comment]
Hi @dp1140a,

I am looking on it and I will release new compatible version as soon as possible.

Thanks for reported issue

**Comment by bednar** [comment]
@dp1140a 

Can you test it with [nifi-influx-database-nar-1.1-SNAPSHOT.nar](https://github.com/influxdata/nifi-influxdb-bundle/releases/download/v1.1-SNAPSHOT/nifi-influx-database-nar-1.1-SNAPSHOT.nar)? This NAR bundle is build over **Apache NiFi 1.9.2** and when I tested it everything works fine for me.

The problem could be caused by multiple version of `nifi-influx-database-nar` in `$NIFI_HOME/work/nar/extensions/` or in `$NIFI_HOME/lib`.

**Comment by dp1140a** [comment]
The new build works with 1.9.2
