### ISSUE TITLE
How can I matchup timestamp at nifi

### ISSUE THREAD

**Issue by gogangipark** [influxdata/nifi-influxdb-bundle#24]
my timestamp format is '20190705073248967' such as yyyyMMddHHmmsssss.

I had tried convert this format to influxdb time.
But I could not convert it. Could you help to resolve this issue.

My conversion code is below.
Timetamp Field : ${REQ_TIME:toDate("yyyyMMddHHmmsssss"):toNumber()}

**Comment by bednar** [comment]
Hi @gogangipark,

Your conversion code will not be work because Apache Nifi evaluating expression over flow file attributes not over record fields.

You could update your record by the [UpdateRecord](https://nifi.apache.org/docs/nifi-docs/components/org.apache.nifi/nifi-standard-nar/1.6.0/org.apache.nifi.processors.standard.UpdateRecord/index.html) processor. 

To add timestamp field to your record use following configuration:

![UpdateRecordSettings](https://user-images.githubusercontent.com/455137/60805928-e668ed00-a181-11e9-97c6-da3e6f2372a0.png)

**Comment by gogangipark** [comment]
thank you for your reply.
I did implement it successfully as your advice.

**Comment by oneofthemany** [comment]
I'm having a similar issue within this thread:

https://github.com/influxdata/nifi-influxdb-bundle/issues/132

Any help would be appreciated
